In [55]:
%matplotlib inline
from jupyterthemes import jtplot
jtplot.style()
import numpy as np
import matplotlib.pyplot as plt

def preprocess():
    raw = np.genfromtxt('monks-1.csv', delimiter=',')
    DATA = raw[:, 0:7]
    X = raw[:, 1:7]
    Y = raw[:, 0]
    return DATA, X, Y

DATA, X, Y = preprocess()

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 2.]
 [1. 1. 1. ... 1. 2. 1.]
 ...
 [1. 3. 3. ... 3. 3. 2.]
 [1. 3. 3. ... 3. 4. 1.]
 [1. 3. 3. ... 3. 4. 2.]] [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 2.]
 [1. 1. 1. 1. 2. 1.]
 ...
 [3. 3. 2. 3. 3. 2.]
 [3. 3. 2. 3. 4. 1.]
 [3. 3. 2. 3. 4. 2.]] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 